In [1]:
import numpy as np


In [4]:
#PROBLEM 1
# 1. Empty 2x2 array
a1 = np.empty((2,2))

# 2. All-one array 4x2
a2 = np.ones((4,2))

# 3. Full array (shape, fill_value)
a3 = np.full((3,3), 7)

# 4. Zeros like another array
ref = np.array([[1,2,3],[4,5,6]])
a4 = np.zeros_like(ref)

# 5. Ones like another array
a5 = np.ones_like(ref)

# 6. Convert list to numpy
new_list = [1,2,3,4]
a6 = np.array(new_list)

a1, a2, a3, a4, a5, a6


(array([[1.66759040e-315, 0.00000000e+000],
        [5.31410685e-317, 6.86299916e-310]]),
 array([[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]]),
 array([[7, 7, 7],
        [7, 7, 7],
        [7, 7, 7]]),
 array([[0, 0, 0],
        [0, 0, 0]]),
 array([[1, 1, 1],
        [1, 1, 1]]),
 array([1, 2, 3, 4]))

In [5]:
#PROBLEM 2
# 1. Values from 10 to 49
p2_1 = np.arange(10,50)

# 2. 3x3 matrix from 0 to 8
p2_2 = np.arange(9).reshape(3,3)

# 3. Identity matrix
p2_3 = np.eye(3)

# 4. Random size-30 array & mean
rand30 = np.random.random(30)
p2_4 = rand30.mean()

# 5. 10x10 random — min & max
rand10 = np.random.random((10,10))
p2_5_min, p2_5_max = rand10.min(), rand10.max()

# 6. Zero array, replace 5th element
arr6 = np.zeros(10)
arr6[4] = 1

# 7. Reverse array
arr7 = np.array([1,2,0,0,4,0])[::-1]

# 8. 2D array with border 1, inside 0
arr8 = np.ones((5,5))
arr8[1:-1,1:-1] = 0

# 9. Checkerboard pattern 8x8
arr9 = np.zeros((8,8))
arr9[1::2,::2] = 1
arr9[::2,1::2] = 1

p2_1, p2_2, p2_3, p2_4, (p2_5_min,p2_5_max), arr6, arr7, arr8, arr9


(array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
        27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
        44, 45, 46, 47, 48, 49]),
 array([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]]),
 array([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]]),
 np.float64(0.511848024060114),
 (np.float64(0.0036787599832937), np.float64(0.9992177500107149)),
 array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.]),
 array([0, 4, 0, 0, 2, 1]),
 array([[1., 1., 1., 1., 1.],
        [1., 0., 0., 0., 1.],
        [1., 0., 0., 0., 1.],
        [1., 0., 0., 0., 1.],
        [1., 1., 1., 1., 1.]]),
 array([[0., 1., 0., 1., 0., 1., 0., 1.],
        [1., 0., 1., 0., 1., 0., 1., 0.],
        [0., 1., 0., 1., 0., 1., 0., 1.],
        [1., 0., 1., 0., 1., 0., 1., 0.],
        [0., 1., 0., 1., 0., 1., 0., 1.],
        [1., 0., 1., 0., 1., 0., 1., 0.],
        [0., 1., 0., 1., 0., 1., 0., 1.],
        [1., 0., 1., 0., 1., 0., 1., 0.]]))

In [7]:
#PROBLEM 3
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11,12])

# 1. Add
add_xy = x + y

# 2. Subtract
sub_xy = x - y

# 3. Multiply by integer
mul_x = x * 3

# 4. Square elements
sq_x = x ** 2

# 5. Dot products
dot_vw = np.dot(v,w)
dot_xv = np.dot(x,v)
dot_xy = np.dot(x,y)

# 6. Concatenate
concat_xy = np.concatenate((x,y), axis=0)   # rows
concat_vw = np.concatenate((v.reshape(-1,1),
                            w.reshape(-1,1)), axis=1)

# 7. Concatenate x and v → error explanation
try:
    np.concatenate((x,v))
except Exception as e:
    error_msg = str(e)

error_msg  # x (2x2) cannot concatenate with v (size 2) along any axis


'all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)'

In [8]:
#PROBLEM 4
A = np.array([[3,4],[7,8]])
B = np.array([[5,3],[2,1]])

# 1. A * A^-1 = I
invA = np.linalg.inv(A)
prove1 = A @ invA  # should be identity

# 2. AB != BA
AB = A @ B
BA = B @ A

# 3. (AB)^T = B^T A^T
lhs = (AB).T
rhs = B.T @ A.T

prove1, AB, BA, lhs, rhs


(array([[1.00000000e+00, 0.00000000e+00],
        [1.77635684e-15, 1.00000000e+00]]),
 array([[23, 13],
        [51, 29]]),
 array([[36, 44],
        [13, 16]]),
 array([[23, 51],
        [13, 29]]),
 array([[23, 51],
        [13, 29]]))

In [10]:
#PROBLEM 5
import time

# size
n = 1_000_000

# List addition
l1 = list(range(n))
l2 = list(range(n))
start = time.time()
l_add = [l1[i] + l2[i] for i in range(n)]
t_list_add = time.time() - start

# Numpy addition
a1 = np.arange(n)
a2 = np.arange(n)
start = time.time()
a_add = a1 + a2
t_np_add = time.time() - start

# Multiplication test
start = time.time()
l_mul = [l1[i] * l2[i] for i in range(n)]
t_list_mul = time.time() - start

start = time.time()
a_mul = a1 * a2
t_np_mul = time.time() - start

# Dot product
start = time.time()
dot_list = sum(l1[i] * l2[i] for i in range(n))
t_list_dot = time.time() - start

start = time.time()
dot_np = np.dot(a1,a2)
t_np_dot = time.time() - start

# Matrix multiplication (1000x1000)
M1 = np.random.random((1000,1000)).tolist()
M2 = np.random.random((1000,1000)).tolist()

start = time.time()
M_list = [[sum(a*b for a,b in zip(r,c)) for c in zip(*M2)] for r in M1]
t_list_mat = time.time() - start

A = np.random.random((1000,1000))
B = np.random.random((1000,1000))

start = time.time()
M_np = A @ B
t_np_mat = time.time() - start

t_list_add, t_np_add, t_list_mul, t_np_mul, t_list_dot, t_np_dot, t_list_mat, t_np_mat


(0.11261391639709473,
 0.006208658218383789,
 0.13667607307434082,
 0.005370378494262695,
 0.10592079162597656,
 0.0017862319946289062,
 186.44585847854614,
 0.06749486923217773)